#!/data/data/com.termux/files/usr/bin/env bash
# Hive OS Termux easy installer (CURRENT MASTER / 1.0.1 repair).
# This is a real product installer: it installs packages, clones/updates the
# repository, installs runtime Python dependencies, creates a global `hive`
# command, and configures Hive OS to autoboot in interactive Termux shells.
#
# NOTE: This installs the CURRENT MASTER branch until hive-os-v1.0.1 is tagged.

set -euo pipefail

REPO_URL="https://github.com/kaibuzz0/TERMUX-RED-TEAM-OPERATING-SYSTEM-.git"
INSTALL_DIR="${HOME}/Hive-Ops"
HIVE_PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
LAUNCHER="${HIVE_PREFIX}/bin/hive"

ensure_pkg() {
    local pkg="$1"
    if ! dpkg -s "${pkg}" >/dev/null 2>&1; then
        echo "[Hive OS] Installing package: ${pkg}"
        pkg install -y "${pkg}"
    fi
}

echo "[Hive OS] Updating package lists..."
pkg update -y

echo "[Hive OS] Installing required Termux packages..."
ensure_pkg git
ensure_pkg python
ensure_pkg python-cryptography

echo "[Hive OS] Cloning CURRENT MASTER (1.0.1 repair)..."
if [ -d "${INSTALL_DIR}/.git" ]; then
    cd "${INSTALL_DIR}"
    git fetch --depth 1 origin master
    git reset --hard origin/master
else
    git clone --depth 1 --branch master "${REPO_URL}" "${INSTALL_DIR}"
fi

cd "${INSTALL_DIR}"

echo "[Hive OS] Installing core runtime Python dependencies..."
if ! python -m pip install -r requirements-runtime.txt; then
    echo "[Hive OS] ERROR: Failed to install core runtime requirements. Stopping." >&2
    exit 1
fi

echo "[Hive OS] Running core command checks..."
python bin/hive --help >/dev/null
python bin/hive --runtime-info --json >/dev/null
python bin/hive config validate
python bin/hive policy status
python bin/hive broker capabilities
python bin/hive ops --json >/dev/null

echo "[Hive OS] Installing global \`hive\` command..."
mkdir -p "${HIVE_PREFIX}/bin"

_is_hive_managed() {
    if [ ! -e "${LAUNCHER}" ]; then
        return 1
    fi
    grep -q "# HIVE_OS_MANAGED_LAUNCHER" "${LAUNCHER}" 2>/dev/null
}

if [ -e "${LAUNCHER}" ] && ! _is_hive_managed; then
    echo "[Hive OS] ERROR: ${LAUNCHER} already exists and is not a Hive-managed launcher." >&2
    echo "            Refusing to overwrite an unrelated command." >&2
    echo "            Move it or set HIVE_PREFIX to an empty directory." >&2
    exit 1
fi

cat > "${LAUNCHER}" <<EOF
#!/data/data/com.termux/files/usr/bin/env bash
# HIVE_OS_MANAGED_LAUNCHER
# Hive OS global launcher (auto-generated by install-termux-easy.sh)
# Forwards all arguments to the installed Hive OS repository launcher.
export HIVE_REPO_ROOT="${INSTALL_DIR}"
exec python "${INSTALL_DIR}/bin/hive" "\$@"
EOF
chmod +x "${LAUNCHER}"

echo "[Hive OS] Configuring autoboot for interactive Termux shells..."
python -m installer.autoboot enable --install-dir "${INSTALL_DIR}"

echo "[Hive OS] Validating installed global command from an unrelated directory..."
(
    cd "${HIVE_PREFIX}/tmp" 2>/dev/null || cd "${HOME}"
    if ! hive --help >/dev/null; then
        echo "[Hive OS] ERROR: Global \`hive\` command does not work." >&2
        exit 1
    fi
)

echo ""
echo "=================================="
echo "  Hive OS installation complete."
echo "=================================="
echo "  Command:  hive"
echo "  Install:  ${INSTALL_DIR}"
echo "  Launcher: ${LAUNCHER}"
echo "  Autoboot: ENABLED"
echo ""
echo "  Open a new Termux session to boot Hive OS."
echo ""
echo "  Disable autoboot: hive autoboot disable"
echo "  Re-enable:        hive autoboot enable"
echo "  Status:           hive autoboot status"
echo ""
echo "  Optional extras (legacy AI/network tools):"
echo "    python -m pip install -r requirements-extras.txt"
