#!/usr/bin/env python3
"""
Hive Swarm Integration - Bidirectional Multi-Agent System

This ties together:
- SwarmOrchestrator (message bus, task delegation)
- AssistantAgent (verification/audit)
- ArchitectAgent (code review)

Usage:
    python3 /root/hive-swarm/hive-swarm.py status
    python3 /root/hive-swarm/hive-swarm.py delegate "Create file parser" to toolsmith
    python3 /root/hive-swarm/hive-swarm.py review /path/to/code.py
    python3 /root/hive-swarm/hive-swarm.py verify task_id
"""
import sys
import os

# Add paths BEFORE any imports
sys.path.insert(0, '/root/hive-swarm')
sys.path.insert(0, '/root/hive-swarm/agents')

from swarm_orchestrator import get_orchestrator, TaskStatus
from assistant_agent import create_assistant_agent
from architect_agent import create_architect_agent

class HiveSwarmCLI:
    """CLI interface to the bidirectional Swarm system."""
    
    def __init__(self):
        self.orchestrator = get_orchestrator()
        self.assistant = create_assistant_agent(self.orchestrator)
        self.architect = create_architect_agent("/root/hive-swarm")
        self._show_banner()
    
    def _show_banner(self):
        print("""
╔══════════════════════════════════════════════════════════╗
║                 HIVE SWARM ACTIVATED                     ║
║                                                          ║
║  Bidirectional Multi-Agent System with Verification     ║
║                                                          ║
║  Agents: orchestrator | assistant | architect          ║
║  Capabilities: delegate → execute → verify → deliver   ║
╚══════════════════════════════════════════════════════════╝
        """)
    
    def status(self):
        """Show current Swarm status."""
        print(self.orchestrator.render_status())
        
        # Show recent messages
        if self.orchestrator.registry.messages:
            print("\n--- Recent Messages ---")
            for msg in self.orchestrator.registry.messages[-5:]:
                print(f"[{msg.type}] {msg.from_agent} → {msg.to_agent}")
    
    def delegate(self, description: str, to_agent: str, requires_verify: bool = True):
        """Delegate a task to an agent."""
        task_id = self.orchestrator.delegate(description, to_agent, requires_verification=requires_verify)
        print(f"\n✓ Task delegated: {task_id}")
        print(f"  Assigned to: {to_agent}")
        print(f"  Verification: {'enabled' if requires_verify else 'disabled'}")
        return task_id
    
    def execute_and_verify(self, description: str, code: str, file_path: str):
        """
        Full flow: Create task → Architect reviews → Assistant verifies
        """
        print(f"\n{'='*50}")
        print(f"SWARM EXECUTION FLOW: {description}")
        print(f"{'='*50}")
        
        # Step 1: Architect reviews code
        print("\n▶ STEP 1: Architecture Review")
        arch_review = self.architect.review_code(file_path, code)
        
        if not arch_review.approved:
            print("\n❌ REJECTED by Architect - fix issues before proceeding")
            return {'approved': False, 'stage': 'architecture'}
        
        # Step 2: Create task
        print("\n▶ STEP 2: Task Delegation")
        task_id = self.orchestrator.delegate(description, "toolsmith")
        
        # Step 3: Simulate completion with result
        print("\n▶ STEP 3: Task Completion")
        result = {
            'description': f'Completed: {description}',
            'deliverables': [file_path],
            'code': code,
            'verified': True,
            'sources': ['Hive Swarm internal'],
            'explanation': 'Code generated by toolsmith agent',
            'risks': arch_review.security_concerns if arch_review.security_concerns else ['None identified']
        }
        
        # Step 4: Submit for verification
        print("\n▶ STEP 4: Submit for Assistant Verification")
        verify_task_id = self.orchestrator.submit_for_verification(
            task_id, "toolsmith", result
        )
        
        # Step 5: Assistant verification
        print("\n▶ STEP 5: Assistant Verification")
        verify_result = self.assistant.verify_task(task_id, description, result)
        
        # Step 6: Report back
        print("\n▶ STEP 6: Verification Report")
        self.orchestrator.report_verification(
            task_id, "assistant", 
            verify_result.approved, 
            verify_result.notes,
            verify_result.corrections
        )
        
        # Final status
        print(f"\n{'='*50}")
        if verify_result.approved:
            print("✓✓✓ TASK FULLY APPROVED AND VERIFIED ✓✓✓")
        else:
            print("❌ TASK REJECTED - REQUIRES REVISION")
        print(f"{'='*50}")
        
        return {
            'task_id': task_id,
            'approved': verify_result.approved,
            'confidence': verify_result.confidence,
            'architect_approved': arch_review.approved,
            'assistant_approved': verify_result.approved
        }
    
    def review_file(self, file_path: str):
        """Review a file with Architect."""
        if not os.path.exists(file_path):
            print(f"Error: File not found: {file_path}")
            return
        
        with open(file_path) as f:
            code = f.read()
        
        review = self.architect.review_code(file_path, code)
        return review.approved
    
    def demo(self):
        """Run a demonstration of the bidirectional system."""
        print("\n" + "="*60)
        print("DEMONSTRATION: Bidirectional Swarm with Verification")
        print("="*60)
        
        # Example 1: Good code that should pass
        print("\n\n--- EXAMPLE 1: Well-structured task ---")
        good_code = '''
#!/usr/bin/env python3
"""Safe file processor with error handling."""
import json
from pathlib import Path
from typing import Dict, List, Optional

def process_json_files(directory: str) -> List[Dict]:
    """
    Safely process JSON files in a directory.
    
    Args:
        directory: Path to directory containing JSON files
        
    Returns:
        List of parsed JSON objects
        
    Raises:
        FileNotFoundError: If directory doesn't exist
    """
    path = Path(directory)
    if not path.exists():
        raise FileNotFoundError(f"Directory not found: {directory}")
    
    results = []
    for json_file in path.glob("*.json"):
        try:
            with open(json_file, 'r') as f:
                data = json.load(f)
                results.append(data)
        except json.JSONDecodeError as e:
            print(f"Error parsing {json_file}: {e}")
            continue
    
    return results
'''
        result1 = self.execute_and_verify(
            "Create safe JSON file processor",
            good_code,
            "/root/hive-swarm/demo/safe_processor.py"
        )
        
        # Example 2: Bad code with issues
        print("\n\n--- EXAMPLE 2: Code with issues ---")
        bad_code = '''
def process_data(user_input):
    result = eval(user_input)  # Security vulnerability
    x = 1
    x = x + 1
    x = x + 1
    x = x + 1  # Too many repeated operations
    return result

class myclass:  # Wrong naming
    def ProcessData(self, data):
        return data
'''
        result2 = self.execute_and_verify(
            "Create data processor (has issues)",
            bad_code,
            "/root/hive-swarm/demo/unsafe_processor.py"
        )
        
        # Example 3: Bidirectional clarification
        print("\n\n--- EXAMPLE 3: Bidirectional Clarification ---")
        print("Simulating agent asking for clarification...")
        task_id = self.orchestrator.delegate(
            "Build automation system", 
            "toolsmith"
        )
        
        # Agent needs clarification
        clarify_msg = self.orchestrator.request_clarification(
            task_id,
            "toolsmith",
            "What type of automation? File processing, build pipeline, or deployment?",
            ["file_processing", "build_pipeline", "deployment"]
        )
        
        print("\n" + "="*60)
        print("DEMO COMPLETE")
        print("="*60)
        print(f"\nSummary:")
        print(f"  - Task 1 (good code): {'APPROVED' if result1['approved'] else 'REJECTED'}")
        print(f"  - Task 2 (bad code): {'APPROVED' if result2['approved'] else 'REJECTED'}")
        print(f"  - Clarification requested: {clarify_msg}")
        print(f"\nRegistry saved to: {self.orchestrator.registry.REGISTRY_PATH}")

def main():
    cli = HiveSwarmCLI()
    
    if len(sys.argv) < 2:
        print("Usage:")
        print("  hive-swarm.py status                 - Show Swarm status")
        print("  hive-swarm.py demo                   - Run demonstration")
        print("  hive-swarm.py delegate 'task' agent  - Delegate task")
        print("  hive-swarm.py review /path/file.py   - Review code")
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "status":
        cli.status()
    
    elif command == "demo":
        cli.demo()
    
    elif command == "delegate" and len(sys.argv) >= 4:
        desc = sys.argv[2]
        agent = sys.argv[3]
        cli.delegate(desc, agent)
    
    elif command == "review" and len(sys.argv) >= 3:
        cli.review_file(sys.argv[2])
    
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)

if __name__ == "__main__":
    main()
